// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr9BMq9NI8zsdPgMqEYoLFPWCJ_13CONg',
    appId: '1:563666769332:web:e92345d7a994e9517ccee1',
    messagingSenderId: '563666769332',
    projectId: 'poultrycare-f816d',
    authDomain: 'poultrycare-f816d.firebaseapp.com',
    databaseURL: 'https://poultrycare-f816d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poultrycare-f816d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwSMbEj4SUsXU_hE8DwIcAp6zgzWGaVD8',
    appId: '1:563666769332:android:f4d99f2528e90e1b7ccee1',
    messagingSenderId: '563666769332',
    projectId: 'poultrycare-f816d',
    databaseURL: 'https://poultrycare-f816d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poultrycare-f816d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN3he8mr3joz62pwPk8KImzacua4iwNKA',
    appId: '1:563666769332:ios:953730ee1547bdf27ccee1',
    messagingSenderId: '563666769332',
    projectId: 'poultrycare-f816d',
    databaseURL: 'https://poultrycare-f816d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poultrycare-f816d.firebasestorage.app',
    iosBundleId: 'com.example.poultrycareApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN3he8mr3joz62pwPk8KImzacua4iwNKA',
    appId: '1:563666769332:ios:953730ee1547bdf27ccee1',
    messagingSenderId: '563666769332',
    projectId: 'poultrycare-f816d',
    databaseURL: 'https://poultrycare-f816d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poultrycare-f816d.firebasestorage.app',
    iosBundleId: 'com.example.poultrycareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr9BMq9NI8zsdPgMqEYoLFPWCJ_13CONg',
    appId: '1:563666769332:web:16606a4eb5778bf77ccee1',
    messagingSenderId: '563666769332',
    projectId: 'poultrycare-f816d',
    authDomain: 'poultrycare-f816d.firebaseapp.com',
    databaseURL: 'https://poultrycare-f816d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poultrycare-f816d.firebasestorage.app',
  );
}
