// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVETPGOXYtc43GfzUqtkWE8L8keDMY078',
    appId: '1:428621787296:web:4fb7de5f70622cd90a99c5',
    messagingSenderId: '428621787296',
    projectId: 'poultrycare-app',
    authDomain: 'poultrycare-app.firebaseapp.com',
    storageBucket: 'poultrycare-app.firebasestorage.app',
    measurementId: 'G-BZ0FBRYEC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT3_AoBQdGbMoqUEOM6Tps80v06QwvfBs',
    appId: '1:428621787296:android:df0781539f308a880a99c5',
    messagingSenderId: '428621787296',
    projectId: 'poultrycare-app',
    databaseURL: 'https://poultrycare-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'poultrycare-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRNCTdRJRZZWBHrSWGuNNJYnwwbGpHwk0',
    appId: '1:428621787296:ios:e926fa6818b1b4c50a99c5',
    messagingSenderId: '428621787296',
    projectId: 'poultrycare-app',
    storageBucket: 'poultrycare-app.firebasestorage.app',
    iosBundleId: 'com.example.poultrycareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRNCTdRJRZZWBHrSWGuNNJYnwwbGpHwk0',
    appId: '1:428621787296:ios:e926fa6818b1b4c50a99c5',
    messagingSenderId: '428621787296',
    projectId: 'poultrycare-app',
    storageBucket: 'poultrycare-app.firebasestorage.app',
    iosBundleId: 'com.example.poultrycareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVETPGOXYtc43GfzUqtkWE8L8keDMY078',
    appId: '1:428621787296:web:3645e76b63c313cf0a99c5',
    messagingSenderId: '428621787296',
    projectId: 'poultrycare-app',
    authDomain: 'poultrycare-app.firebaseapp.com',
    storageBucket: 'poultrycare-app.firebasestorage.app',
    measurementId: 'G-D1NT0H69RY',
  );
}
